### ISSUE TITLE
Create AbstractAwsMojo

### ISSUE THREAD

**Issue by RoKish** [davidmoten/aws-maven-plugin#14]
All MOJOs have a common structure, i. e. they all define the same parameters to configure proxy and AWS authentication, they all create `Proxy` and `AwsKeyPair` objects etc. 

I think it's a good idea to create `AbstractAwsMojo` with an abstract method `#execute(AwsKeyPair, Proxy, String)` which all the other MOJOs will have to override. The `execute()` method of `AbstractAwsMojo` will be handling `Proxy` and `AwsKeyPair` objects creation and then calling `#execute(AwsKeyPair, Proxy, String)`. This will allow to get rid of a lot of repetitions and add descriptions for all these common parameters.

Does it make sense?

**Comment by davidmoten** [comment]
Yes it sure does make sense. A bit of technical debt begging to be sorted. Would you like to make a PR?
