### ISSUE TITLE
Deploy directory: all the files are given public read permission

### ISSUE THREAD

**Issue by beautylim** [davidmoten/aws-maven-plugin#18]
I don't want to give files public read permission, could remove it? or any suggestions do you have? thanks

**Comment by davidmoten** [comment]
Doesn't happen for me, I deployed items today. Is the bucket configured for public read?

**Comment by davidmoten** [comment]
Someone must have configured a bucket policy for public read as per
https://stackoverflow.com/questions/19176926/how-to-make-all-objects-in-aws-s3-bucket-public-by-default

**Comment by beautylim** [comment]
I mean when upload directory, all files of the directory will be give public read permission. I saw it from readme

**Comment by beautylim** [comment]
My s3 bucket blocked all public access, when use deployS3 goal, it will fail with f goal com.github.davidmoten:aws-maven-plugin:0.2.24:deployS3 failed: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 93. So i need remove the public read setting at deployS3 mojo.

**Comment by davidmoten** [comment]
Oh, sorry, just looked at the readme and saw the method you refer to. I'll have a look.

**Comment by davidmoten** [comment]
Now you can turn off publicRead using `<publicRead>false</publicRead>` in the configuration. Deployed to Maven Central version 0.2.25. This will not attempt to apply an ACL to the uploaded files but use the bucket default.

**Comment by beautylim** [comment]
Thanks a lot!
